### ISSUE TITLE
No Usable Clang Found

### ISSUE THREAD

**Issue by compicat** [blacksky3/llvm-minimal-git#1]
First of all, thanks for your amazing work. I ve installed your last version from your repo, but getting below warning. Llvm-git is also giving same warning, only llvm from extra repo is compiling without issue. What can be the reason? 

![Screenshot_2023-03-28_20-11-57](https://user-images.githubusercontent.com/49899468/228316958-c32ae6e2-d5bb-479d-9d79-d801f73ae1b3.png)

And here is the log:

[Uploading meson-log.txt…]()

**Comment by blacksky3** [comment]
Just upgraded the entire repo. Let me know if you have some problem. I'll build every packages in a clean chroot and push them to the repo mention in the README. Keep me in touch

**Comment by compicat** [comment]
> Just upgraded the entire repo. Let me know if you have some problem. I'll build every packages in a clean chroot and push them to the repo mention in the README. Keep me in touch

thank you for fast action. Gonna try and report. Btw there is small typo mistakes at pacman install command at this part at readme. Just for your information to make things easier for first time finders this amazing repo.

[llvm-minimal-git]
SigLevel = Optional TrustAll
Server = https://repo.blacksky3.com/$arch/$repo

sudo pacman -S **llvm-mininal-git** llvm-libs-minimal-git **lib32-llvm-miniaml-git** lib32-llvm-libs-minimal-git libclc-minimal-git spirv-llvm-translator-minimal-git spirv-headers-git spirv-tools-git glslang-git

**Comment by compicat** [comment]
> Just upgraded the entire repo. Let me know if you have some problem. I'll build every packages in a clean chroot and push them to the repo mention in the README. Keep me in touch

Unfortunately, same error with same log. I m using this tool to compile mesa fyi:

https://github.com/Frogging-Family/mesa-git

**Comment by blacksky3** [comment]
And if you compile with mesa provided by this repo? https://github.com/blacksky3/llvm-minimal-git/blob/main/mesa/

**Comment by compicat** [comment]
If i compile from here, i m getting this patch error:

  -> Applying patch 5a271b8ff8d1b1a560847718a806f652b9040e34.patch...
patching file src/vulkan/util/vk_extensions.py
Hunk #1 FAILED at 17.
Hunk #2 FAILED at 44.
Hunk #3 FAILED at 192.
3 out of 3 hunks FAILED -- saving rejects to file src/vulkan/util/vk_extensions.py.rej

**Comment by blacksky3** [comment]
Thanks for reporting

These path were from this issue : https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21806

remove the 2 patches in the pkgbuild and disable vulkan=beta

Let me know if you have some problems

**Comment by blacksky3** [comment]
Wich version or commit of mesa you trying to build?

**Comment by compicat** [comment]
> Wich version or commit of mesa you trying to build?

I was about to write that. I need specifically Mesa 22.2.5 which is commit eef77e355a4c4a0810cea1bc618ad62aff3f4e17 because my gpu has only 1.3 vulkan api with this release (HD4000). Later then 22.2.5 has vulkan 1.2 api, so dxvk is not working with releases newer than 22.2.5

If i change pkgbuild according to my commit, it does not update mesa git. Is there any solution for this specific commit?

**Comment by blacksky3** [comment]
You should open an issue in official mesa repo. 

Since this repo follow upstream llvm and upstream mesa I cant support for older version. 

I'll mark this issue closed. If you find a solution feel free to make a pull request

**Comment by compicat** [comment]
Thanks again for your all help again.

**Comment by compicat** [comment]
Ok, i returned the devel mesa after some arrangements in my system. Now i m having only this error during compiling after all patches:

../mesa/src/gallium/frontends/clover/llvm/invocation.cpp:31:10: fatal error: llvm/Transforms/IPO/PassManagerBuilder.h: No such file or directory
   31 | #include <llvm/Transforms/IPO/PassManagerBuilder.h>

Can you help?

**Comment by blacksky3** [comment]
Disable gallium-opencl

gallium-opencl=disabled

**Comment by compicat** [comment]
Thank you. I ve finally compiled successfully.
